### PR TITLE
fix parse body when the charset is set

### PR DESCRIPTION
**Pull request by dancespiele**
this doesn't contemplate the possibility to set charset, for example `application/json; charset=utf-8`, with this PR fix it

### CODE REVIEW

**Comment by Dashron** [comment]
What are your thoughts on using https://www.npmjs.com/package/content-type instead of indexOf? If you can't get to it, I can probably hack it out later tonight. I use it in my new API framework here: https://github.com/Dashron/roads-api/blob/master/src/Resource/contentTypeResolver.js

**Comment by dancespiele** [comment]
Sorry I will try to do it. I didn't have time.

**Comment by dancespiele** [comment]
@Dashron I was try how can I implement it with content-type module but I didn't get it. If you know you could implement it.

**Comment by Dashron** [comment]
No worries. I might have time this week, worst case I can probably handle it during a flight on Friday.

**Comment by Dashron** [comment]
Just pushed up a fix, let me know if it does the job!

https://github.com/Dashron/roads/commit/28e154d7ba910aeac1573596493c980184716175

**Comment by dancespiele** [comment]
It works, thank you @Dashron.

**Pull request closed without merging**
